// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	FirstName  string  `json:"firstName"`
	MiddleName *string `json:"middleName,omitempty"`
	LastName   string  `json:"lastName"`
	Email      string  `json:"email"`
	Phone      *string `json:"phone,omitempty"`
	Province   *string `json:"province,omitempty"`
	Ward       *string `json:"ward,omitempty"`
	Password   string  `json:"password"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type UpdateUserInput struct {
	FirstName  *string `json:"firstName,omitempty"`
	MiddleName *string `json:"middleName,omitempty"`
	LastName   *string `json:"lastName,omitempty"`
	Phone      *string `json:"phone,omitempty"`
	Province   *string `json:"province,omitempty"`
	Ward       *string `json:"ward,omitempty"`
}

type User struct {
	ID         string  `json:"id"`
	FirstName  string  `json:"firstName"`
	MiddleName *string `json:"middleName,omitempty"`
	LastName   string  `json:"lastName"`
	Email      string  `json:"email"`
	Phone      *string `json:"phone,omitempty"`
	Province   *string `json:"province,omitempty"`
	Ward       *string `json:"ward,omitempty"`
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
}

type UserPagination struct {
	Items       []*User `json:"items"`
	TotalItems  int32   `json:"totalItems"`
	TotalPages  int32   `json:"totalPages"`
	CurrentPage int32   `json:"currentPage"`
	PageSize    int32   `json:"pageSize"`
}
